export type AppPage =
  | 'landing'
  | 'dashboard'
  | 'stats'
  | 'settings'
  | 'pricing'
  | 'documents'
  | 'candidates'
  | 'offer'
  | 'admin-agencies'
  | 'admin-invite-codes'
  | 'admin-feature-requests'
